reviewers:
  defaults:
    - maksymkv25
    - romanesent
    - artemShelest
    - chupaSV
options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 2
