from . import sale_estimate
from . import sale_estimate_stage
from . import product_attribute
from . import purchase_requisition
from . import product_price_sheet
from . import sale_order
from . import purchase_order
from . import res_partner
from . import crm_stage
from . import crm_lead
from . import delivery_carrier
from . import stock_rule
