version: '2'
services:
  regency-web:
    container_name: regency-web
    image: regency_web
    build: ../..
    depends_on:
      - regency-db
    user: odoo
    ports:
      - "8109:8069"
    volumes:
      - ../../addons:/mnt/extra-addons
      - ../../opsway/regency-enterprise:/mnt/opsway/regency-enterprise
      - ../../opsway/submodules:/mnt/opsway/submodules
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./data:/var/lib/odoo
    environment:
      - HOST=regency-db
      - USER=odoo
      - PASSWORD=myodoo
  regency-db:
    container_name: regency-db
    ports:
      - "5542:5432"
    image: postgres:14.5
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_DB=postgres
    volumes:
      - /var/lib/postgresql/data